sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tLiHax29J3UhQSdKzfp
    bucket-name: cangqiong-xjy
    access-key-secret: Sl6fwGQ9i3U8uz2OHDCATcOBkPPG8S